import Data.Char (isUpper, isLower)

filepath = "selfdescription.hs"

main :: IO()
main = do
  programm <- readFile filepath
  putStrLn "-- This text is generated by itself."
  putStrLn programm
  putStrLn . describeText $ programm

describeText :: String -> String
describeText str =
  "-- There are " ++ show numberCaps ++ " uppercase, " ++ show minuskel ++ " lower  and " ++ show others ++ " other charakters in this Text."
  where
    numberCaps :: Int
    numberCaps = length . filter isUpper $ str

    minuskel :: Int
    minuskel = length . filter isLower $ str

    others :: Int
    others = chars - numberCaps - minuskel
    
    chars :: Int
    chars = length str
