-- This text is generated by itself.import Data.Char (isUpper, isLower)

filepath = "selfdescription.hs"

main :: IO()
main = do
  programm <- readFile filepath
  let analysation = analyzeText programm
  putStrLn analysation
  writeFile filepath analysation

analyzeText :: String -> String
analyzeText str =
   "-- This text is generated by itself."
   ++ str
   ++ "-- There are " ++ show numberCaps ++ " uppercase, " ++ show minuskel ++ " lower  and " ++ show others ++ " other charakters in this Text."
  where
    numberCaps :: Int
    numberCaps = length . filter isUpper $ str

    minuskel :: Int
    minuskel = length . filter isLower $ str

    others :: Int
    others = chars - numberCaps - minuskel
    
    chars :: Int
    chars = length str
-- There are 28 uppercase, 445 lower  and 248 other charakters in this Text.